// <auto-generated />
using System;
using System.Collections.Generic;
using Mendeleev.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mendeleev.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mendeleev.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_action_created_at");

                    b.HasIndex("StaffId", "Id")
                        .HasDatabaseName("ix_audit_log_staff_id_id");

                    b.HasIndex("TargetUserId", "Id")
                        .HasDatabaseName("ix_audit_log_target_user_id_id");

                    b.ToTable("audit_log", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Broadcasts.Broadcast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BotBlocked")
                        .HasColumnType("integer")
                        .HasColumnName("bot_blocked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_staff_id");

                    b.Property<long>("CursorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("cursor_user_id");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<long>("ReportChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_chat_id");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("segment");

                    b.Property<int>("Sent")
                        .HasColumnType("integer")
                        .HasColumnName("sent");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<bool>("WithUpdateButton")
                        .HasColumnType("boolean")
                        .HasColumnName("with_update_button");

                    b.HasKey("Id")
                        .HasName("pk_broadcasts");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_broadcasts_status");

                    b.ToTable("broadcasts", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Devices.DeviceReset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DevicesRemoved")
                        .HasColumnType("integer")
                        .HasColumnName("devices_removed");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("initiated_by");

                    b.Property<long?>("StaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("staff_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_resets");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_device_resets_user_id_created_at");

                    b.ToTable("device_resets", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Notifications.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_dedup_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConfirmationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("confirmation_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("DaysGranted")
                        .HasColumnType("integer")
                        .HasColumnName("days_granted");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<DateTime?>("LinkExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("link_expires_at");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_review");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("ReceiptId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_payments_tariff_id");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_provider_provider_payment_id")
                        .HasFilter("provider_payment_id IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_payments_status_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_payments_user_id_created_at");

                    b.ToTable("payments", "public", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");

                            t.HasCheckConstraint("ck_payments_days_granted", "days_granted > 0");
                        });
                });

            modelBuilder.Entity("Mendeleev.Domain.Payments.PaymentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_payment_events");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_payment_events_created_at");

                    b.HasIndex("PaymentId", "Id")
                        .HasDatabaseName("ix_payment_events_payment_id_id");

                    b.ToTable("payment_events", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Staff.StaffMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedByStaffId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_staff_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_telegram_id");

                    b.ToTable("staff", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AccessIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_issued_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpiredReason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("expired_reason");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("FirstConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_connected_at");

                    b.Property<string>("PanelShortUuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("panel_short_uuid");

                    b.Property<int?>("PanelUserId")
                        .HasColumnType("integer")
                        .HasColumnName("panel_user_id");

                    b.Property<Guid>("PanelVlessUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("panel_vless_uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubscriptionUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subscription_url");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sync_state");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<int>("TariffId")
                        .HasColumnType("integer")
                        .HasColumnName("tariff_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PanelShortUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_panel_short_uuid");

                    b.HasIndex("PanelUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_panel_user_id")
                        .HasFilter("panel_user_id IS NOT NULL");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_subscriptions_tariff_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_status_expires_at");

                    b.ToTable("subscriptions", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Tariffs.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<int>("DeviceLimit")
                        .HasColumnType("integer")
                        .HasColumnName("device_limit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<Guid>>("PanelSquads")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("panel_squads");

                    b.Property<int>("PeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("period_days");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.Property<long?>("TrafficLimitBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_limit_bytes");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tariffs_code");

                    b.ToTable("tariffs", "public", t =>
                        {
                            t.HasCheckConstraint("ck_tariffs_device_limit", "device_limit > 0");

                            t.HasCheckConstraint("ck_tariffs_period_days", "period_days > 0");

                            t.HasCheckConstraint("ck_tariffs_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("Mendeleev.Domain.Traffic.TrafficDaily", b =>
                {
                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<long>("LifetimeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("lifetime_bytes");

                    b.HasKey("SubscriptionId", "Day")
                        .HasName("pk_traffic_daily");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_traffic_daily_day");

                    b.ToTable("traffic_daily", "public", t =>
                        {
                            t.HasCheckConstraint("ck_traffic_daily_bytes", "bytes >= 0");
                        });
                });

            modelBuilder.Entity("Mendeleev.Domain.Users.LinkCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_link_codes");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("ix_link_codes_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_link_codes_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_link_codes_user_id");

                    b.ToTable("link_codes", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_key_hash");

                    b.Property<DateTime?>("AccountKeyIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_key_issued_at");

                    b.Property<bool>("BotBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("bot_blocked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<Guid>("SessionStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_stamp")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_started_at");

                    b.Property<bool>("TrialUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("trial_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_account_key_hash")
                        .HasFilter("account_key_hash IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_id")
                        .HasFilter("telegram_id IS NOT NULL");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Mendeleev.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_status_next_attempt_at");

                    b.ToTable("outbox_messages", "public");
                });

            modelBuilder.Entity("Mendeleev.Infrastructure.Telegram.ProcessedTelegramUpdate", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("update_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("UpdateId")
                        .HasName("pk_processed_telegram_updates");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_processed_telegram_updates_received_at");

                    b.ToTable("processed_telegram_updates", "public");
                });

            modelBuilder.Entity("Mendeleev.Domain.Devices.DeviceReset", b =>
                {
                    b.HasOne("Mendeleev.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_resets_users_user_id");
                });

            modelBuilder.Entity("Mendeleev.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Mendeleev.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("Mendeleev.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Mendeleev.Domain.Tariffs.Tariff", null)
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_tariffs_tariff_id");

                    b.HasOne("Mendeleev.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_user_id");
                });

            modelBuilder.Entity("Mendeleev.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("Mendeleev.Domain.Tariffs.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_tariffs_tariff_id");

                    b.HasOne("Mendeleev.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Mendeleev.Domain.Subscriptions.Subscription", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Mendeleev.Domain.Traffic.TrafficDaily", b =>
                {
                    b.HasOne("Mendeleev.Domain.Subscriptions.Subscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_traffic_daily_subscriptions_subscription_id");
                });

            modelBuilder.Entity("Mendeleev.Domain.Users.LinkCode", b =>
                {
                    b.HasOne("Mendeleev.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_codes_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
