using Mendeleev.Domain.Tariffs;
using Mendeleev.SharedKernel;

namespace Mendeleev.Domain.Subscriptions
{
    /// <summary>
    /// The user's current right of access — one row per user (FR-SUB-03). Our database is the source of
    /// truth for the term and status; the panel only executes the desired state that the
    /// <see cref="SubscriptionChangedDomainEvent"/> handler pushes to it (ТЗ 10, «База сервиса — источник истины»).
    /// </summary>
    /// <remarks>
    /// Every mutating path must hold the user's row lock (SELECT … FOR UPDATE on <c>users</c>) while it
    /// changes the subscription: two payments arriving at once are then applied one after the other and
    /// the term is extended twice (ТЗ 22, «Правило продления»).
    /// </remarks>
    public sealed class Subscription : Entity
    {
        private Subscription() { }

        public long Id { get; private set; }

        public long UserId { get; private set; }

        public int TariffId { get; private set; }

        /// <summary>Must be loaded (Include) before calling any method that changes the status.</summary>
        public Tariff Tariff { get; private set; } = null!;

        public SubscriptionStatus Status { get; private set; }

        /// <summary>Start of the current uninterrupted period.</summary>
        public DateTime StartedAt { get; private set; }

        public DateTime ExpiresAt { get; private set; }

        public ExpiredReason? ExpiredReason { get; private set; }

        /// <summary>Numeric id of the Remnawave 3.x user; null until the first successful sync.</summary>
        public int? PanelUserId { get; private set; }

        /// <summary>
        /// Generated by us and passed on create, so the panel can be rebuilt from our database without
        /// changing users' links (ТЗ 40, «Бэкапы и восстановление»).
        /// </summary>
        public string PanelShortUuid { get; private set; } = string.Empty;

        public Guid PanelVlessUuid { get; private set; }

        public string? SubscriptionUrl { get; private set; }

        /// <summary>When the panel user was first created for the current link — the onboarding clock.</summary>
        public DateTime? AccessIssuedAt { get; private set; }

        public DateTime? FirstConnectedAt { get; private set; }

        public SyncState SyncState { get; private set; }

        public DateTime? SyncedAt { get; private set; }

        public DateTime CreatedAt { get; private set; }

        public DateTime UpdatedAt { get; private set; }

        /// <summary>Trial and active subscriptions let traffic through.</summary>
        public bool GrantsAccess => Status is SubscriptionStatus.Trial or SubscriptionStatus.Active;

        /// <summary>
        /// Access is granted here but may not be in the panel yet: the link was never issued, or the last
        /// change has not reached the panel (it is unreachable). The user sees «Доступ активируется в течение
        /// нескольких минут» (ТЗ 22, 23: «Панель недоступна…»).
        /// </summary>
        public bool AccessPending => GrantsAccess && (SubscriptionUrl is null || SyncState == SyncState.Pending);

        /// <summary>States in which a panel user must exist (a disabled user stays in the panel, switched off).</summary>
        public bool RequiresPanelUser =>
            Status is SubscriptionStatus.Trial or SubscriptionStatus.Active or SubscriptionStatus.Disabled;

        /// <summary>The link, QR and instructions are shown for trial, active and expired-within-30-days (ТЗ 27).</summary>
        public bool LinkVisible =>
            SubscriptionUrl is not null
            && Status is SubscriptionStatus.Trial or SubscriptionStatus.Active or SubscriptionStatus.Expired;

        public int DaysLeft(DateTime utcNow) =>
            ExpiresAt <= utcNow ? 0 : (int)Math.Ceiling((ExpiresAt - utcNow).TotalDays);

        public static Subscription StartTrial(long userId, Tariff trial, DateTime utcNow)
        {
            if (!trial.IsTrial)
            {
                throw new ArgumentException("A trial subscription needs the trial tariff.", nameof(trial));
            }

            Subscription subscription = New(userId, trial, SubscriptionStatus.Trial, utcNow.AddDays(trial.PeriodDays), utcNow);
            subscription.Changed(SubscriptionNotice.AccessIssued, $"trial:{utcNow.Ticks}", utcNow);
            return subscription;
        }

        /// <summary>The first payment of a user who never had a subscription (FR-SUB-03).</summary>
        public static Subscription CreatePaid(long userId, Tariff tariff, int days, Guid paymentId, DateTime utcNow)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(days);

            Subscription subscription = New(userId, tariff, SubscriptionStatus.Active, utcNow.AddDays(days), utcNow);
            subscription.Changed(SubscriptionNotice.AccessIssued, paymentId.ToString("N"), utcNow);
            return subscription;
        }

        /// <summary>Bonus days of a promo code for a user who never had a subscription (ТЗ 22, «Промокоды»).</summary>
        public static Subscription CreateFromPromo(long userId, Tariff tariff, int days, string noticeKey, DateTime utcNow)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(days);
            if (tariff.IsTrial)
            {
                throw new ArgumentException("Bonus days are days of a paid tariff.", nameof(tariff));
            }

            Subscription subscription = New(userId, tariff, SubscriptionStatus.Active, utcNow.AddDays(days), utcNow);
            subscription.Changed(SubscriptionNotice.AccessIssued, noticeKey, utcNow);
            return subscription;
        }

        /// <summary>
        /// Bonus days of a promo code (FR-SUB-15): the term grows by FR-SUB-04 like after a payment. The days are
        /// days of the paid service, so a trial becomes an active subscription on <paramref name="paidTariff"/>
        /// without the trial's traffic limit; an expired one comes back with the same link, an archived one with
        /// a new link if the panel user is already gone. A disabled (blocked) subscription only gets the days.
        /// </summary>
        public void ApplyBonusDays(Tariff paidTariff, int days, string noticeKey, DateTime utcNow)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(days);
            if (paidTariff.IsTrial)
            {
                throw new ArgumentException("Bonus days are days of a paid tariff.", nameof(paidTariff));
            }

            SubscriptionNotice notice = SubscriptionNotice.PromoBonus;

            switch (Status)
            {
                case SubscriptionStatus.Archived:
                    if (Reactivate(utcNow) == SubscriptionNotice.AccessIssued)
                    {
                        notice = SubscriptionNotice.AccessIssued;
                    }
                    ExpiresAt = utcNow.AddDays(days);
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Expired:
                    StartedAt = utcNow;
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    ExpiredReason = null;
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Trial:
                case SubscriptionStatus.Active:
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Disabled:
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    break;
            }

            if (Tariff.IsTrial)
            {
                TariffId = paidTariff.Id;
                Tariff = paidTariff;
            }
            Changed(notice, noticeKey, utcNow);
        }

        /// <summary>
        /// FR-SUB-04: <c>new expiry = max(now, current expiry) + period</c>. A payment during the trial turns
        /// it into an active subscription and lifts the traffic limit; the remaining trial days are kept
        /// (FR-SUB-05). A payment within 30 days after expiry keeps the same link (FR-SUB-08); after
        /// archiving a new link is issued (FR-SUB-09). A blocked user's payment extends the term but the
        /// subscription stays disabled (ТЗ 22, «Бизнес-правила»).
        /// </summary>
        public void ApplyPayment(Tariff tariff, int days, Guid paymentId, DateTime utcNow)
        {
            ArgumentOutOfRangeException.ThrowIfNegativeOrZero(days);

            SubscriptionNotice notice = SubscriptionNotice.PaymentSucceeded;

            switch (Status)
            {
                case SubscriptionStatus.Archived:
                    notice = Reactivate(utcNow);
                    ExpiresAt = utcNow.AddDays(days);
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Expired:
                    StartedAt = utcNow;
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    ExpiredReason = null;
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Trial:
                case SubscriptionStatus.Active:
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    Status = SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Disabled:
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    break;
            }

            TariffId = tariff.Id;
            Tariff = tariff;
            Changed(notice, paymentId.ToString("N"), utcNow);
        }

        /// <summary>
        /// Compensation by a staff member (FR-SUB-12), or one of many after an outage (FR-SUB-16: <paramref name="reason"/>
        /// goes into the user's message). The limits by role are checked by the caller; an expired subscription comes
        /// back to life, an archived one gets a new link.
        /// </summary>
        public Result ExtendByStaff(int days, string noticeKey, DateTime utcNow, string? reason = null)
        {
            if (days <= 0)
            {
                return Result.Failure(SubscriptionErrors.InvalidDays);
            }

            SubscriptionNotice notice = reason is null ? SubscriptionNotice.Compensated : SubscriptionNotice.MassCompensated;

            switch (Status)
            {
                case SubscriptionStatus.Archived:
                    SubscriptionNotice reactivation = Reactivate(utcNow);
                    notice = reactivation == SubscriptionNotice.AccessIssued ? reactivation : notice;
                    ExpiresAt = utcNow.AddDays(days);
                    Status = Tariff.IsTrial ? SubscriptionStatus.Trial : SubscriptionStatus.Active;
                    break;

                case SubscriptionStatus.Expired:
                    StartedAt = utcNow;
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    ExpiredReason = null;
                    Status = Tariff.IsTrial ? SubscriptionStatus.Trial : SubscriptionStatus.Active;
                    break;

                default:
                    ExpiresAt = Later(utcNow, ExpiresAt).AddDays(days);
                    break;
            }

            Changed(notice, noticeKey, utcNow, reason);
            return Result.Success();
        }

        /// <summary>
        /// A refund marked by an admin (FR-PAY-16; решение 07.10 — как в оферте). <paramref name="daysToRemove"/>
        /// null: the unused days were returned (п. 6.3) and access ends now. Otherwise the payment was erroneous or
        /// duplicate (п. 6.2): the term loses those days, but never ends before now. The term never grows; an
        /// expired or archived subscription is left as it is; a disabled one only gets the shorter term.
        /// </summary>
        /// <returns>False when there was nothing to take back.</returns>
        public bool ApplyRefund(int? daysToRemove, string noticeKey, DateTime utcNow)
        {
            if (Status is SubscriptionStatus.Expired or SubscriptionStatus.Archived || ExpiresAt <= utcNow)
            {
                return false;
            }

            DateTime target = daysToRemove is int days ? Later(utcNow, ExpiresAt.AddDays(-days)) : utcNow;
            ExpiresAt = target < ExpiresAt ? target : ExpiresAt;

            bool ended = ExpiresAt <= utcNow;
            if (ended && GrantsAccess)
            {
                Status = SubscriptionStatus.Expired;
                ExpiredReason = Subscriptions.ExpiredReason.Refund;
            }

            Changed(ended ? SubscriptionNotice.RefundEnded : SubscriptionNotice.RefundShortened, noticeKey, utcNow);
            return true;
        }

        /// <summary>
        /// Moves a trial or active subscription to <see cref="SubscriptionStatus.Expired"/>: by time once the
        /// term is over (FR-SUB-06), or by traffic when the panel reports that the trial ran out of its 10 GB.
        /// </summary>
        public bool TryExpire(ExpiredReason reason, DateTime utcNow)
        {
            if (!GrantsAccess)
            {
                return false;
            }
            if (reason == Subscriptions.ExpiredReason.Time && ExpiresAt > utcNow)
            {
                return false;
            }

            Status = SubscriptionStatus.Expired;
            ExpiredReason = reason;
            UpdatedAt = utcNow;
            Raise(new SubscriptionChangedDomainEvent(
                UserId,
                reason == Subscriptions.ExpiredReason.Traffic ? SubscriptionNotice.TrafficExhausted : SubscriptionNotice.Expired,
                ExpiresAt.Ticks.ToString(System.Globalization.CultureInfo.InvariantCulture)));
            return true;
        }

        /// <summary>Account blocked by staff: access is switched off in the panel (FR-SUB-13).</summary>
        public void Disable(DateTime utcNow)
        {
            if (Status is SubscriptionStatus.Disabled or SubscriptionStatus.Archived)
            {
                return;
            }
            Status = SubscriptionStatus.Disabled;
            Changed(SubscriptionNotice.None, null, utcNow);
        }

        /// <summary>Unblocking returns trial/active or expired depending on the term (FR-SUB-13).</summary>
        public void Enable(DateTime utcNow)
        {
            if (Status != SubscriptionStatus.Disabled)
            {
                return;
            }

            if (ExpiresAt > utcNow)
            {
                Status = Tariff.IsTrial ? SubscriptionStatus.Trial : SubscriptionStatus.Active;
                ExpiredReason = null;
            }
            else
            {
                Status = SubscriptionStatus.Expired;
                ExpiredReason = Subscriptions.ExpiredReason.Time;
            }
            Changed(SubscriptionNotice.None, null, utcNow);
        }

        /// <summary>30 days after expiry the panel user is deleted and the link stops working (FR-SUB-09).</summary>
        public bool TryArchive(int retentionDays, DateTime utcNow)
        {
            if (Status != SubscriptionStatus.Expired || ExpiresAt.AddDays(retentionDays) > utcNow)
            {
                return false;
            }
            Status = SubscriptionStatus.Archived;
            Changed(SubscriptionNotice.None, null, utcNow);
            return true;
        }

        /// <summary>Records the result of a link reissue done in the panel (FR-PNL-16).</summary>
        public void ApplyReissuedLink(string shortUuid, Guid vlessUuid, string subscriptionUrl, DateTime utcNow)
        {
            PanelShortUuid = shortUuid;
            PanelVlessUuid = vlessUuid;
            SubscriptionUrl = subscriptionUrl;
            FirstConnectedAt = null;
            AccessIssuedAt = utcNow;
            Changed(SubscriptionNotice.LinkReissued, shortUuid, utcNow);
        }

        /// <summary>Asks for the full desired state to be pushed again — used when drift is detected.</summary>
        public void RequestResync(DateTime utcNow)
        {
            Changed(SubscriptionNotice.None, null, utcNow);
        }

        public void MarkSynced(int panelUserId, Guid vlessUuid, string subscriptionUrl, DateTime utcNow)
        {
            PanelUserId = panelUserId;
            PanelVlessUuid = vlessUuid;
            SubscriptionUrl = subscriptionUrl;
            AccessIssuedAt ??= utcNow;
            SyncState = SyncState.Synced;
            SyncedAt = utcNow;
            UpdatedAt = utcNow;
        }

        /// <summary>
        /// The panel now builds the link on another domain (the subscriptions domain was switched to the
        /// reserve, runbook «Заблокирован домен подписок»). The secret part stays: nothing to resync.
        /// </summary>
        public bool RefreshSubscriptionUrl(string subscriptionUrl, DateTime utcNow)
        {
            if (SubscriptionUrl is null || string.Equals(SubscriptionUrl, subscriptionUrl, StringComparison.Ordinal))
            {
                return false;
            }
            SubscriptionUrl = subscriptionUrl;
            UpdatedAt = utcNow;
            return true;
        }

        /// <summary>Nothing has to exist in the panel for this state (for example, expired and never synced).</summary>
        public void MarkNothingToSync(DateTime utcNow)
        {
            SyncState = SyncState.Synced;
            SyncedAt = utcNow;
            UpdatedAt = utcNow;
        }

        public void MarkSyncFailed(DateTime utcNow)
        {
            SyncState = SyncState.Failed;
            UpdatedAt = utcNow;
        }

        public void MarkPanelUserDeleted(DateTime utcNow)
        {
            PanelUserId = null;
            SubscriptionUrl = null;
            AccessIssuedAt = null;
            FirstConnectedAt = null;
            SyncState = SyncState.Synced;
            SyncedAt = utcNow;
            UpdatedAt = utcNow;
        }

        /// <summary>
        /// The panel lost the user (404 on update). The same short UUID is passed on re-create, so the
        /// user's link keeps working.
        /// </summary>
        public void ForgetPanelUser(DateTime utcNow)
        {
            PanelUserId = null;
            SyncState = SyncState.Pending;
            UpdatedAt = utcNow;
        }

        public void MarkFirstConnected(DateTime connectedAt)
        {
            FirstConnectedAt ??= connectedAt;
        }

        private static Subscription New(long userId, Tariff tariff, SubscriptionStatus status, DateTime expiresAt, DateTime utcNow) => new()
        {
            UserId = userId,
            TariffId = tariff.Id,
            Tariff = tariff,
            Status = status,
            StartedAt = utcNow,
            ExpiresAt = expiresAt,
            PanelShortUuid = PanelIdentifiers.NewShortUuid(),
            PanelVlessUuid = Guid.NewGuid(),
            SyncState = SyncState.Pending,
            CreatedAt = utcNow,
            UpdatedAt = utcNow,
        };

        /// <summary>
        /// Leaves the archive. If the panel user is already deleted, the next sync creates a new one under a
        /// new link; if deletion has not happened yet, the old user and link are simply reused.
        /// </summary>
        private SubscriptionNotice Reactivate(DateTime utcNow)
        {
            StartedAt = utcNow;
            ExpiredReason = null;

            if (PanelUserId is not null)
            {
                return SubscriptionNotice.PaymentSucceeded;
            }

            PanelShortUuid = PanelIdentifiers.NewShortUuid();
            PanelVlessUuid = Guid.NewGuid();
            SubscriptionUrl = null;
            AccessIssuedAt = null;
            FirstConnectedAt = null;
            return SubscriptionNotice.AccessIssued;
        }

        private void Changed(SubscriptionNotice notice, string? noticeKey, DateTime utcNow, string? detail = null)
        {
            SyncState = SyncState.Pending;
            UpdatedAt = utcNow;
            Raise(new SubscriptionChangedDomainEvent(UserId, notice, noticeKey, detail));
        }

        private static DateTime Later(DateTime a, DateTime b) => a > b ? a : b;
    }
}
